import { ListingCategory } from '../../listings/listing-category.enum';

export interface SeedListing {
  title: string;
  description: string;
  category: ListingCategory;
  location: string;
  address: string;
  pricePerNight: number;
  guests: number;
  bedrooms: number;
  beds: number;
  bathrooms: number;
  rating: number;
  reviewsCount: number;
  images: string[];
  amenities: string[];
  isFeatured: boolean;
}

export const seedListings: SeedListing[] = [
  {
    title: 'Modern Apartment in Tashkent',
    description:
      'A beautiful modern apartment in the heart of Tashkent with city views and fast WiFi.',
    category: ListingCategory.APARTMENT,
    location: 'Tashkent',
    address: 'Yunusabad District, Tashkent',
    pricePerNight: 80,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    rating: 4.8,
    reviewsCount: 124,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'Parking'],
    isFeatured: true,
  },
  {
    title: 'Cozy Studio near Amir Timur Square',
    description:
      'Compact and stylish studio perfect for solo travelers exploring central Tashkent.',
    category: ListingCategory.APARTMENT,
    location: 'Tashkent',
    address: 'Amir Timur Square, Tashkent',
    pricePerNight: 45,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    rating: 4.5,
    reviewsCount: 89,
    images: [
      'https://images.unsplash.com/photo-1536376072261-38c75010a6d9?w=800',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    ],
    amenities: ['WiFi', 'Kitchen', 'Air conditioning'],
    isFeatured: false,
  },
  {
    title: 'Luxury Penthouse with Panoramic Views',
    description:
      'Spacious penthouse with floor-to-ceiling windows overlooking the Tashkent skyline.',
    category: ListingCategory.APARTMENT,
    location: 'Tashkent',
    address: 'Mirzo Ulugbek District, Tashkent',
    pricePerNight: 220,
    guests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    rating: 4.9,
    reviewsCount: 56,
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
    ],
    amenities: [
      'WiFi',
      'Kitchen',
      'Air conditioning',
      'Parking',
      'Pool',
      'Gym',
    ],
    isFeatured: true,
  },
  {
    title: 'Family Home in Chilanzar',
    description:
      'Comfortable family home with a private garden, ideal for longer stays in Tashkent.',
    category: ListingCategory.HOUSE,
    location: 'Tashkent',
    address: 'Chilanzar District, Tashkent',
    pricePerNight: 95,
    guests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    rating: 4.6,
    reviewsCount: 72,
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
      'https://images.unsplash.com/photo-1605276374104-de6862b76978?w=800',
    ],
    amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'Parking', 'Garden'],
    isFeatured: false,
  },
  {
    title: 'Boutique Hotel Room in Tashkent Center',
    description:
      'Elegant hotel room with daily housekeeping and a rooftop breakfast lounge.',
    category: ListingCategory.HOTEL,
    location: 'Tashkent',
    address: 'Shaykhontohur District, Tashkent',
    pricePerNight: 65,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    rating: 4.4,
    reviewsCount: 201,
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800',
    ],
    amenities: ['WiFi', 'Air conditioning', 'Breakfast', 'Room service'],
    isFeatured: false,
  },
  {
    title: 'Historic House near Registan Square',
    description:
      'Traditional Samarkand house with carved wooden details, steps from Registan.',
    category: ListingCategory.HOUSE,
    location: 'Samarkand',
    address: 'Registan Square Area, Samarkand',
    pricePerNight: 110,
    guests: 5,
    bedrooms: 2,
    beds: 3,
    bathrooms: 2,
    rating: 4.9,
    reviewsCount: 167,
    images: [
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
    ],
    amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'Garden', 'Breakfast'],
    isFeatured: true,
  },
  {
    title: 'Silk Road Guest Apartment',
    description:
      'Bright apartment decorated with local textiles, close to Bibi-Khanym Mosque.',
    category: ListingCategory.APARTMENT,
    location: 'Samarkand',
    address: 'Tashkent Street, Samarkand',
    pricePerNight: 70,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    rating: 4.7,
    reviewsCount: 98,
    images: [
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    ],
    amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'Washer'],
    isFeatured: false,
  },
  {
    title: 'Courtyard Villa in Samarkand',
    description:
      'Private villa with a tiled courtyard, perfect for families visiting the ancient city.',
    category: ListingCategory.VILLA,
    location: 'Samarkand',
    address: 'Siab Bazaar Area, Samarkand',
    pricePerNight: 180,
    guests: 8,
    bedrooms: 4,
    beds: 5,
    bathrooms: 3,
    rating: 4.8,
    reviewsCount: 43,
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
    ],
    amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'Parking', 'Pool'],
    isFeatured: true,
  },
  {
    title: 'Budget Stay near Gur-e-Amir',
    description:
      'Affordable and clean room for backpackers exploring Samarkand on a budget.',
    category: ListingCategory.HOTEL,
    location: 'Samarkand',
    address: 'Gur-e-Amir Mausoleum Area, Samarkand',
    pricePerNight: 35,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    rating: 4.2,
    reviewsCount: 134,
    images: [
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800',
      'https://images.unsplash.com/photo-1590071246553-efc936caa8a4?w=800',
    ],
    amenities: ['WiFi', 'Air conditioning', 'Breakfast'],
    isFeatured: false,
  },
  {
    title: 'Artisan Loft in Old Samarkand',
    description:
      'Loft-style stay surrounded by craft workshops and narrow old-town lanes.',
    category: ListingCategory.APARTMENT,
    location: 'Samarkand',
    address: 'Old City, Samarkand',
    pricePerNight: 88,
    guests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    rating: 4.6,
    reviewsCount: 61,
    images: [
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800',
      'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800',
    ],
    amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'Workspace'],
    isFeatured: false,
  },
  {
    title: 'Old City Guesthouse in Bukhara',
    description:
      'Charming guesthouse inside the UNESCO-listed old city walls of Bukhara.',
    category: ListingCategory.HOUSE,
    location: 'Bukhara',
    address: 'Lyabi-Hauz Plaza, Bukhara',
    pricePerNight: 75,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    rating: 4.8,
    reviewsCount: 112,
    images: [
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800',
      'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800',
    ],
    amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'Breakfast', 'Garden'],
    isFeatured: true,
  },
  {
    title: 'Merchant House with Blue Dome Views',
    description:
      'Restored merchant house offering authentic architecture and rooftop tea service.',
    category: ListingCategory.HOUSE,
    location: 'Bukhara',
    address: 'Po-i-Kalyan Complex, Bukhara',
    pricePerNight: 120,
    guests: 5,
    bedrooms: 2,
    beds: 3,
    bathrooms: 2,
    rating: 4.9,
    reviewsCount: 88,
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
      'https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=800',
    ],
    amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'Breakfast'],
    isFeatured: false,
  },
  {
    title: 'Desert Oasis Apartment',
    description:
      'Cool and quiet apartment ideal after a day exploring Bukhara’s historic mosques.',
    category: ListingCategory.APARTMENT,
    location: 'Bukhara',
    address: 'Ark Fortress Area, Bukhara',
    pricePerNight: 55,
    guests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    rating: 4.5,
    reviewsCount: 76,
    images: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
      'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800',
    ],
    amenities: ['WiFi', 'Kitchen', 'Air conditioning'],
    isFeatured: false,
  },
  {
    title: 'Caravanserai Style Hotel Suite',
    description:
      'Spacious suite inspired by Silk Road caravanserais, with traditional decor.',
    category: ListingCategory.HOTEL,
    location: 'Bukhara',
    address: 'Trading Dome District, Bukhara',
    pricePerNight: 140,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    rating: 4.7,
    reviewsCount: 54,
    images: [
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800',
      'https://images.unsplash.com/photo-1598928506311-c55ded91a2c3?w=800',
    ],
    amenities: ['WiFi', 'Air conditioning', 'Breakfast', 'Room service'],
    isFeatured: false,
  },
  {
    title: 'Walled City Retreat in Khiva',
    description:
      'Stay inside Itchan Kala with views of minarets and ancient city walls.',
    category: ListingCategory.HOUSE,
    location: 'Khiva',
    address: 'Itchan Kala, Khiva',
    pricePerNight: 90,
    guests: 4,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    rating: 4.8,
    reviewsCount: 67,
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
      'https://images.unsplash.com/photo-1600566753086-00f18fb576b9?w=800',
    ],
    amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'Breakfast'],
    isFeatured: true,
  },
  {
    title: 'Desert Fort View Apartment',
    description:
      'Quiet apartment near Kalta Minor minaret with sunset views over Khiva.',
    category: ListingCategory.APARTMENT,
    location: 'Khiva',
    address: 'Kalta Minor Area, Khiva',
    pricePerNight: 60,
    guests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    rating: 4.6,
    reviewsCount: 49,
    images: [
      'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=800',
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800',
    ],
    amenities: ['WiFi', 'Kitchen', 'Air conditioning'],
    isFeatured: false,
  },
  {
    title: 'Silk Workshop Guest Room',
    description:
      'Unique room above a traditional silk workshop in the heart of Khiva.',
    category: ListingCategory.HOTEL,
    location: 'Khiva',
    address: 'Pahlavan Mahmud Street, Khiva',
    pricePerNight: 48,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    rating: 4.4,
    reviewsCount: 38,
    images: [
      'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800',
      'https://images.unsplash.com/photo-1611892440502-42a792e2848b?w=800',
    ],
    amenities: ['WiFi', 'Air conditioning', 'Breakfast'],
    isFeatured: false,
  },
  {
    title: 'Mountain Cabin in Chimgan',
    description:
      'Rustic cabin surrounded by pine forests with a fireplace and mountain trails.',
    category: ListingCategory.CABIN,
    location: 'Chimgan',
    address: 'Chimgan Valley, Tashkent Region',
    pricePerNight: 130,
    guests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    rating: 4.9,
    reviewsCount: 91,
    images: [
      'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800',
      'https://images.unsplash.com/photo-1518780664697-55e3ad049233?w=800',
      'https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=800',
    ],
    amenities: ['WiFi', 'Kitchen', 'Fireplace', 'Parking', 'Mountain view'],
    isFeatured: true,
  },
  {
    title: 'Ski Lodge near Charvak Lake',
    description:
      'Cozy lodge perfect for winter sports weekends and summer lake trips.',
    category: ListingCategory.CABIN,
    location: 'Chimgan',
    address: 'Charvak Reservoir Area, Chimgan',
    pricePerNight: 150,
    guests: 8,
    bedrooms: 4,
    beds: 5,
    bathrooms: 2,
    rating: 4.7,
    reviewsCount: 64,
    images: [
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
    ],
    amenities: ['WiFi', 'Kitchen', 'Fireplace', 'Parking', 'Hot tub'],
    isFeatured: false,
  },
  {
    title: 'Alpine Retreat with Terrace',
    description:
      'Modern mountain home with a large terrace overlooking the Ugam mountain range.',
    category: ListingCategory.VILLA,
    location: 'Chimgan',
    address: 'Beldersay Resort Area, Chimgan',
    pricePerNight: 250,
    guests: 10,
    bedrooms: 5,
    beds: 6,
    bathrooms: 3,
    rating: 4.9,
    reviewsCount: 37,
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800',
    ],
    amenities: ['WiFi', 'Kitchen', 'Fireplace', 'Parking', 'BBQ grill'],
    isFeatured: true,
  },
  {
    title: 'Seaside Inspired Villa in Fergana Valley',
    description:
      'Open-plan villa with bright interiors and a pool, inspired by resort living.',
    category: ListingCategory.VILLA,
    location: 'Fergana',
    address: 'Fergana Valley, Uzbekistan',
    pricePerNight: 200,
    guests: 8,
    bedrooms: 4,
    beds: 5,
    bathrooms: 3,
    rating: 4.8,
    reviewsCount: 29,
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
      'https://images.unsplash.com/photo-1605276374104-de6862b76978?w=800',
    ],
    amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'Pool', 'Parking'],
    isFeatured: false,
  },
  {
    title: 'Minimalist Urban Loft',
    description:
      'Design-focused loft with clean lines, ideal for remote work and city breaks.',
    category: ListingCategory.APARTMENT,
    location: 'Tashkent',
    address: 'Yakkasaray District, Tashkent',
    pricePerNight: 72,
    guests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    rating: 4.5,
    reviewsCount: 83,
    images: [
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800',
    ],
    amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'Workspace'],
    isFeatured: false,
  },
  {
    title: 'Countryside House near Nurata',
    description:
      'Peaceful countryside escape between desert and mountains with starry night skies.',
    category: ListingCategory.HOUSE,
    location: 'Nurata',
    address: 'Nurata District, Navoiy Region',
    pricePerNight: 58,
    guests: 5,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    rating: 4.3,
    reviewsCount: 41,
    images: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
      'https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=800',
    ],
    amenities: ['WiFi', 'Kitchen', 'Parking', 'Garden', 'BBQ grill'],
    isFeatured: false,
  },
  {
    title: 'Lakefront Cabin Retreat',
    description:
      'Quiet cabin on the water with kayaking access and panoramic sunset views.',
    category: ListingCategory.CABIN,
    location: 'Charvak',
    address: 'Charvak Lake Shore, Tashkent Region',
    pricePerNight: 165,
    guests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    rating: 4.7,
    reviewsCount: 52,
    images: [
      'https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=800',
      'https://images.unsplash.com/photo-1449158743715-0cb8908142be?w=800',
    ],
    amenities: ['WiFi', 'Kitchen', 'Parking', 'Lake access', 'Kayaks'],
    isFeatured: false,
  },
  {
    title: 'Business Hotel near Tashkent Airport',
    description:
      'Convenient hotel stay for short business trips with airport shuttle service.',
    category: ListingCategory.HOTEL,
    location: 'Tashkent',
    address: 'Airport District, Tashkent',
    pricePerNight: 85,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    rating: 4.1,
    reviewsCount: 156,
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
      'https://images.unsplash.com/photo-1584132967334-10e028bd69d7?w=800',
    ],
    amenities: ['WiFi', 'Air conditioning', 'Breakfast', 'Airport shuttle'],
    isFeatured: false,
  },
];
